bind r source-file ~/.tmux.conf \; display "Reloaded tmux config!"

unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix
bind Space last-pane
bind w last-window
bind C-p previous-window
bind C-n next-window
bind R                                      \
    move-window -r\;                        \
    display-message "Windows reordered..."
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.

set -g base-index 1
set -g mouse on
set -g history-limit 50000
set -g display-time 2000
set -g status-interval 5
set -g focus-events on
setw -g aggressive-resize on
set -s escape-time 0
# set -g detach-on-destroy off

# Title Terminal settings
set -g allow-passthrough on
set -g set-titles on
set -g set-titles-string "tmux #S - #{pane_title}"

set -g pane-border-status top
set -g pane-border-format "#{pane_index} #{pane_title}"

# Window renaming
setw -g automatic-rename on
set -g automatic-rename-format "#{pane_title}"
bind , command-prompt -I "#W" "rename-window '%%'; setw automatic-rename off"
bind < setw automatic-rename on \; display "Window's name reset"


set -g @catppuccin_window_status_style "basic"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Configure Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# status right look and feel
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=#{@cpu_bg_color},fg=#{@cpu_fg_color}] #{cpu_icon} #{cpu_percentage}"
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#[bg=#{@cpu_bg_color},fg=#{@cpu_fg_color}] #{ram_icon} #{ram_percentage} "
set -ga status-right "#[bg=#{@thm_mantle},fg=#{@thm_overlay_0}, none]│"
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M"

# bootstrap tpm
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "absolute-centre"

# pane border look and feel
setw -g pane-active-border-style "bg=#{@thm_bg},fg=#{@thm_overlay_0}"
setw -g pane-border-style "bg=#{@thm_bg},fg=#{@thm_surface_0}"
setw -g pane-border-lines single

set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_rosewater}"
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_peach}"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"

set -g window-status-current-style "bg=#{@thm_peach},fg=#{@thm_bg},bold"


run ~/.tmux/plugins/catppuccin/catppuccin.tmux
run-shell ~/.tmux/plugins/tmux-cpu/cpu.tmux
